### ISSUE TITLE
How to run this project on windows ?

### ISSUE THREAD

**Issue by Doimatcuabautroi** [huguei/p5-Net-Address-IP-Cipher#3]
Ex me, I don't have any knowledge about (built, make. compile, etc ...) 
So can you make a "release" file ?

**Comment by huguei** [comment]
I'm not sure how to release a windows version, but Activestate has it on their package system for windows: http://code.activestate.com/ppm/Net-Address-IP-Cipher/
Does it work for you?

**Comment by Doimatcuabautroi** [comment]
Sorry :((, can you make a video turtorial about run your project on win
I ran your project as (http://code.activestate.com/ppm/Net-Address-IP-Cipher/)
But after that, I don't know what i have to do :((
![asa](https://user-images.githubusercontent.com/18320809/47898286-c329c780-dea7-11e8-93d7-84da2d5b320e.jpg)

**Comment by Doimatcuabautroi** [comment]
When i open ipleak.net, i see my ip is not changed, thus i didnt run ipcipher 

This project is encrypt ip address, so my activities on internet is incongto, right ?
Ex: google.com don't know me(133.173.282.2:real ip) access their website
Is My knowledge about this project true ?

**Comment by huguei** [comment]
No, sorry! This project is a library to be used for the Perl programming language. It doesn't encrypt by its own.
You need a proxy, or VPN, or Tor to encrypt your address.
